AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - spec/**/*
    - Gemfile
    - Gemfile.lock
  TargetRubyVersion: '2.7'